# Numerical Python (Numpy) and Python Data Analysis (Pandas)

8/29/2024

Numerical Python - array object?

In [1]:
import numpy as np #imports all Numpy functions

ndArrays are the multidimensional containers of items of same type and size

includes 1, 2, and 3, dimensions

dTypes include: integer, float, complex, bool, object, string

storage of datasets:

calls: shape(size,size,size,...)

shape(size) -> 1 Dimensional

shape(size,size) -> 2 Dimensional

shape(size,size,size) -> 3 Dimensional

array.shape

axes: 0 (1st dimension), 1, (2nd dimension), 2 (3rd dimension)

In [3]:
#creating arrays
#this is for vectors
#one dimensional
#axis 0
el = np.array([1,2,3])
el

array([1, 2, 3])

In [5]:
#this is for matrices
#two dimensional
#axes 0 and 1
psy = np.array([(2.4,-1.5,1.1),(2.3,-2.5,-5.6)])
psy

array([[ 2.4, -1.5,  1.1],
       [ 2.3, -2.5, -5.6]])

In [7]:
#this is for tensors(?)
#three dimensional
#axes 0, 1, 2
kongroo = np.array([[(1.1,2,3.4),(7,2.5,9)],[(1,2,3),(9,8,7)]])
kongroo

array([[[1.1, 2. , 3.4],
        [7. , 2.5, 9. ]],

       [[1. , 2. , 3. ],
        [9. , 8. , 7. ]]])

In [11]:
#Create an array by defining the rows and columms m x n x p
x = np.zeros([2,3])
x

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
x = np.ones([2,3])
x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
x = np.zeros([2,3,4])
x

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [15]:
#results a Range -> np.linspace(first,last,interval)
z = np.arange(3,7,0.5)
z
#doesnt include 7

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [20]:
#np.linspace(first,last,number of samples)
np.linspace(3,7,10)
#includes 7

array([3.        , 3.44444444, 3.88888889, 4.33333333, 4.77777778,
       5.22222222, 5.66666667, 6.11111111, 6.55555556, 7.        ])

In [21]:
np.full((5,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [22]:
np.full((5,3,5),5)

array([[[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]],

       [[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]],

       [[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]],

       [[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]],

       [[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]]])

In [24]:
#np.full((1st dimension,2nd dimension,3rd dimension, ... , nth dimension),number that you want to fill)
np.full((2,2,2,2),2)

array([[[[2, 2],
         [2, 2]],

        [[2, 2],
         [2, 2]]],


       [[[2, 2],
         [2, 2]],

        [[2, 2],
         [2, 2]]]])

In [25]:
#identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
np.random.random((2,3))

array([[0.33004105, 0.24476441, 0.97446392],
       [0.97824389, 0.14900417, 0.34056335]])

In [27]:
data = np.load("epk.npy")
data

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [28]:
data.shape

(2, 2, 3)

In [29]:
data.ndim

3

In [30]:
data.size

12

**Python Demo 2: Arithmetic and Logical Operation on Arrays**

In [32]:
a = np.array([(2,4,6),(8,10,12)])
a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [33]:
b = np.array([(4,9),(16,25),(36,49)])
b

array([[ 4,  9],
       [16, 25],
       [36, 49]])

In [34]:
c = np.array([2,3,5])
c

array([2, 3, 5])

In [36]:
c-a

array([[ 0, -1, -1],
       [-6, -7, -7]])

In [37]:
a+c

array([[ 4,  7, 11],
       [10, 13, 17]])

In [38]:
a*c

array([[ 4, 12, 30],
       [16, 30, 60]])

In [39]:
c*a

array([[ 4, 12, 30],
       [16, 30, 60]])

In [40]:
a/c

array([[1.        , 1.33333333, 1.2       ],
       [4.        , 3.33333333, 2.4       ]])

In [ ]:
#these work above since they have the same number of columns / same row size

In [41]:
a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [42]:
b

array([[ 4,  9],
       [16, 25],
       [36, 49]])

In [43]:
np.exp(b)

array([[5.45981500e+01, 8.10308393e+03],
       [8.88611052e+06, 7.20048993e+10],
       [4.31123155e+15, 1.90734657e+21]])

In [44]:
np.sqrt(b)

array([[2., 3.],
       [4., 5.],
       [6., 7.]])

In [45]:
np.cos(b)

array([[-0.65364362, -0.91113026],
       [-0.95765948,  0.99120281],
       [-0.12796369,  0.30059254]])

In [46]:
np.log(b)

array([[1.38629436, 2.19722458],
       [2.77258872, 3.21887582],
       [3.58351894, 3.8918203 ]])

In [47]:
np.sinh(b)

array([[2.72899172e+01, 4.05154190e+03],
       [4.44305526e+06, 3.60024497e+10],
       [2.15561577e+15, 9.53673286e+20]])

In [48]:
a = np.array([2,3,5])
a

array([2, 3, 5])

In [49]:
b = np.array([(1,2,5),(4,5,6),(7,8,9)])
b

array([[1, 2, 5],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
c = a
c

array([2, 3, 5])

In [51]:
a == b

array([[False, False,  True],
       [False, False, False],
       [False, False, False]])

In [52]:
b < 7

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

In [53]:
a > 2

array([False,  True,  True])

In [54]:
np.array_equal(a,b)

False

In [55]:
np.array_equal(a,c)

True

Python Demonstration 3: Subsetting, Slicing, and Indexing ndArrays

Subset = obtains a specific value

Slice = obtains a portion of the data structure

Index = obtains specific values with conditions

In [57]:
A = np.array([(1,2,3),(4,5,6),(7,8,9)])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Subsetting - getting a certain element from the array or structure

In [59]:
A[1,1]

5

In [60]:
A[2,1]

8

Slicing - getting the portion from an array or structure

In [61]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
A[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [63]:
A[0:3,2]

array([3, 6, 9])

In [64]:
A[1]

array([4, 5, 6])

Indexing - getting a certain element or portion depending on the conditions

In [66]:
A[A<7]

array([1, 2, 3, 4, 5, 6])

In [67]:
A[A>2]

array([3, 4, 5, 6, 7, 8, 9])

In [72]:
A[A==5]

array([5])

Python Demo 4 - ndArray Manipulation

In [73]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [85]:
b = np.array([(4,6,5),(1,2,3)])
b

array([[4, 6, 5],
       [1, 2, 3]])

In [76]:
c = np.linspace(10,20,3)
c

array([10., 15., 20.])

In [77]:
d = np.full((2,2),np.pi)
d

array([[3.14159265, 3.14159265],
       [3.14159265, 3.14159265]])

In [78]:
e = np.eye(2)
e

array([[1., 0.],
       [0., 1.]])

In [91]:
a.sort()
a

array([1, 2, 3])

In [84]:
b

array([[4, 5, 6],
       [1, 2, 3]])

In [87]:
b.sort(axis=0) #by row
b

array([[1, 2, 3],
       [4, 6, 5]])

In [89]:
b.sort(axis=1) #by column
b

array([[1, 2, 3],
       [4, 5, 6]])

In [92]:
np.shape(b)

(2, 3)

In [93]:
b.reshape(2,3).shape

(2, 3)

In [94]:
b.resize(3,2)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [96]:
d

array([[3.14159265, 3.14159265],
       [3.14159265, 3.14159265]])

In [97]:
e

array([[1., 0.],
       [0., 1.]])

In [98]:
np.append(e,d)

array([1.        , 0.        , 0.        , 1.        , 3.14159265,
       3.14159265, 3.14159265, 3.14159265])

In [99]:
a


array([1, 2, 3])

In [105]:
np.insert(a,1,5)

array([1, 5, 2, 3])

In [106]:
np.delete(a,[2]) # a = [1,2,3], removes 3 at location 2

array([1, 2])

In [108]:
np.concatenate((a,c),axis=0)

array([ 1.,  2.,  3., 10., 15., 20.])

In [109]:
np.vstack((a,c))

array([[ 1.,  2.,  3.],
       [10., 15., 20.]])

In [110]:
np.hstack((d,e))

array([[3.14159265, 3.14159265, 1.        , 0.        ],
       [3.14159265, 3.14159265, 0.        , 1.        ]])

In [111]:
np.hsplit(a,3)

[array([1]), array([2]), array([3])]

In [112]:
np.vsplit(e,2)

[array([[1., 0.]]), array([[0., 1.]])]